/*
 * SVGeezy.js 1.0
*/
var svgeezy=function(){return{init:function(a,b){this.avoid=a||!1,this.filetype=b||"png",this.svgSupport=this.supportsSvg(),this.svgSupport||(this.images=document.getElementsByTagName("img"),this.imgL=this.images.length,this.fallbacks())},fallbacks:function(){for(;this.imgL--;)if(!this.hasClass(this.images[this.imgL],this.avoid)||!this.avoid){var a=this.images[this.imgL].getAttribute("src");if(null===a)continue;if("svg"==this.getFileExt(a)){var b=a.replace(".svg","."+this.filetype);this.images[this.imgL].setAttribute("src",b)}}},getFileExt:function(a){var b=a.split(".").pop();return-1!==b.indexOf("?")&&(b=b.split("?")[0]),b},hasClass:function(a,b){return(" "+a.className+" ").indexOf(" "+b+" ")>-1},supportsSvg:function(){return document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image","1.1")}}}();

/*
 * Wufoo
*/
function initForm(){initializeFocus();var a=document.getElementsByTagName("form")[0];addEvent(a,"submit",disableSubmitButton),ifInstructs(),showRangeCounters()}function disableSubmitButton(){document.getElementById("saveForm").disabled=!0}function initializeFocus(){var a=getElementsByClassName(document,"*","field");for(i=0;i<a.length;i++)"radio"==a[i].type||"checkbox"==a[i].type?(a[i].onclick=function(){highlight(this,4)},a[i].onfocus=function(){highlight(this,4)}):a[i].onfocus=a[i].className.match("addr")||a[i].className.match("other")?function(){highlight(this,3)}:function(){highlight(this,2)}}function highlight(a,b){if(2==b)var c=a.parentNode.parentNode;if(3==b)var c=a.parentNode.parentNode.parentNode;if(4==b)var c=a.parentNode.parentNode.parentNode.parentNode;addClassName(c,"focused",!0);var d=getElementsByClassName(document,"*","focused");for(i=0;i<d.length;i++)d[i]!=c&&removeClassName(d[i],"focused")}function ifInstructs(){var a=document.getElementById("public");if(a){removeClassName(a,"noI");var b=getElementsByClassName(document,"*","instruct");""==b&&addClassName(a,"noI",!0),a.offsetWidth<=450&&addClassName(a,"altInstruct",!0)}}function showRangeCounters(){for(counters=getElementsByClassName(document,"em","currently"),i=0;i<counters.length;i++)counters[i].style.display="inline"}function validateRange(a,b){if(document.getElementById("rangeUsedMsg"+a)){var c=document.getElementById("Field"+a),d=document.getElementById("rangeUsedMsg"+a);switch(b){case"character":d.innerHTML=c.value.length;break;case"word":var e=c.value;e=e.replace(/\n/g," ");var f=e.split(" "),g=0;for(i=0;i<f.length;i++)""!=f[i].replace(/\s+$/,"")&&g++;d.innerHTML=g;break;case"digit":d.innerHTML=c.value.length}}}function getElementsByClassName(a,b,c){var d="*"==b&&a.all?a.all:a.getElementsByTagName(b),e=new Array;c=c.replace(/\-/g,"\\-");for(var g,f=new RegExp("(^|\\s)"+c+"(\\s|$)"),h=0;h<d.length;h++)g=d[h],f.test(g.className)&&e.push(g);return e}function addClassName(a,b,c){if(a.className){var d=a.className.split(" ");if(c)for(var e=b.toUpperCase(),f=0;f<d.length;f++)d[f].toUpperCase()==e&&(d.splice(f,1),f--);d[d.length]=b,a.className=d.join(" ")}else a.className=b}function removeClassName(a,b){if(a.className){for(var c=a.className.split(" "),d=b.toUpperCase(),e=0;e<c.length;e++)c[e].toUpperCase()==d&&(c.splice(e,1),e--);a.className=c.join(" ")}}function addEvent(a,b,c){a.attachEvent?(a["e"+b+c]=c,a[b+c]=function(){a["e"+b+c](window.event)},a.attachEvent("on"+b,a[b+c])):a.addEventListener(b,c,!1)}addEvent(window,"load",initForm);var highlight_array=new Array;


/*
 * FitText
*/
!function(a){a.fn.fitText=function(b,c){var d=b||1,e=a.extend({minFontSize:Number.NEGATIVE_INFINITY,maxFontSize:Number.POSITIVE_INFINITY},c);return this.each(function(){var b=a(this),c=function(){b.css("font-size",Math.max(Math.min(b.width()/(10*d),parseFloat(e.maxFontSize)),parseFloat(e.minFontSize)))};c(),a(window).on("resize.fittext orientationchange.fittext",c)})}}(jQuery);
